my_shop/adminapp/urls.py
from django.urls import path
from adminapp import views as admin_views

app_name = 'adminapp'
urlpatterns = [
    path('products/create/<int:pk>/', admin_views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>', admin_views.ProductsListView.as_view(), name='product_list'),
    path('products/update/<int:pk>/', admin_views.ProductUpdateView.as_view(), name='product_edit'),
    path('products/delete/<int:pk>/', admin_views.ProductDeleteView.as_view(), name='product_delete'),
    path('products/detail/<int:pk>/',admin_views.ProductDetailView.as_view(),name='product_detail'),

    path('categories/create/', admin_views.CreateCategory.as_view(), name='category_create'),
    path('categories/', admin_views.categories, name='category_list'),
    path('categories/update/<int:pk>/', admin_views.EditCategory.as_view(), name='category_edit'),
    path('categories/delete/<int:pk>/', admin_views.DeleteCategory.as_view(), name='category_delete'),

    path('users/create/', admin_views.user_create, name='user_create'),
    path('users/', admin_views.UsersListView.as_view(), name='user_list'),
    path('users/update/<int:pk>/', admin_views.user_update, name='user_edit'),
    path('users/delete/<int:pk>/', admin_views.user_delete, name='user_delete'),
]

my_shop/authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit, verify

app_name = 'authapp'
urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<email>/<key>/', verify, name='verify'),
]

my_shop/my_shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp

urlpatterns = [
    path('control/', admin.site.urls),

    path('', mainapp.index, name='index'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('orderapp.urls', namespace='order'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

my_shop/adminapp/models.py
from django.db import models

# Create your models here.

my_shop/adminapp/forms.py
from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from django import forms

from mainapp.models import Product, ProductCategory


class ShopUsersAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

            if field_name == 'password':
                field.widget = forms.HiddenInput()


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        print(fields)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control'
            else:
                field.widget.attrs['class'] = 'form-control'


class CategoryCreateForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', min_value=0, max_value=90, initial=0, required=False)

    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            elif isinstance(field.widget, forms.DateTimeInput):
                field.widget.attrs['class'] = 'form-control'
            else:
                field.widget.attrs['class'] = 'form-control'

my_shop/adminapp/views.py
from django.db.models import F
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy
# Create your views here.
from adminapp.forms import ShopUsersAdminEditForm, ProductEditForm, CategoryCreateForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db import connection


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)

        db_profile_by_type(sender, 'UPDATE', connection.queries)


class ProductCreateView(CreateView):
    model = Product
    template_name = 'adminapp/product_form.html'
    form_class = ProductEditForm
    success_url = reverse_lazy('adminapp:category_list')


class ProductsListView(ListView):
    model = Product
    template_name = 'adminapp/product.html'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['category'] = get_object_or_404(ProductCategory, pk=self.kwargs.get('pk'))
        return context_data

    def get_queryset(self):
        return Product.objects.filter(category__pk=self.kwargs.get('pk'))


class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'adminapp/product_form.html'
    form_class = ProductEditForm

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs['pk'])
        return reverse('adminapp:product_list', args=[product_item.category_id])


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs['pk'])
        return reverse('adminapp:product_list', args=[product_item.category_id])


class ProductDetailView(DeleteView):
    model = Product
    template_name = 'adminapp/product_detail.html'


class CreateCategory(CreateView):
    model = ProductCategory
    form_class = CategoryCreateForm
    success_url = reverse_lazy('adminapp:category_list')
    template_name = 'adminapp/category_create.html'


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    context = {
        'object_list': ProductCategory.objects.all().order_by('-is_active')
    }
    return render(request, 'adminapp/categories.html', context)


# @user_passes_test(lambda u: u.is_superuser)
# def category_update(request):
#     context = {
#
#     }
#     return render(request, '', context)
class EditCategory(UpdateView):
    model = ProductCategory
    success_url = reverse_lazy('adminapp:category_list')
    form_class = CategoryCreateForm
    template_name = 'adminapp/category_form.html'

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data.get('discount')
            if discount:
                self.object.product_set.update(
                    price=F('price') * (1 - discount / 100)
                )
        return super().form_valid(form)


# @user_passes_test(lambda u: u.is_superuser)
# def category_delete(request):
#     context = {
#
#     }
#     return render(request, '', context)

class DeleteCategory(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('adminapp:category_list')


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)

        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('adminapp:user_list'))
    else:
        user_form = ShopUserRegisterForm()

    context = {
        'form': user_form,
    }
    return render(request, 'adminapp/user_form.html', context)


# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     context = {
#         'object_list': ShopUser.objects.all().order_by('-is_active')
#     }
#     return render(request, 'adminapp/users.html', context)


class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    current_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        user_form = ShopUsersAdminEditForm(request.POST, request.FILES, instance=current_user)

        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('adminapp:user_list'))
    else:
        user_form = ShopUsersAdminEditForm(instance=current_user)

    context = {
        'form': user_form,
    }
    return render(request, 'adminapp/user_form.html', context)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    current_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        if current_user.is_active:
            current_user.is_active = False
        else:
            current_user.is_active = True
        current_user.save()
        return HttpResponseRedirect(reverse('adminapp:user_list'))
    context = {
        'object': current_user,
    }
    return render(request, 'adminapp/user_delete.html', context)

my_shop/adminapp/templates/adminapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.rtl.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static '/js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static '/js/basket.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="h2 text-center head">
        Админка
    </div>
    {% block menu %}
        <div class="admin_menu">
            {% include 'adminapp/includes/inc_menu.html' %}
        </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
</div>

</body>
</html>

my_shop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="categories_list">
    <button class="new_category">
      <a href={% url 'adminapp:category_create' %}>
        новая категория
      </a>
    </button>

    {% for object in object_list %}
      <div class="category_record">
        <div class="category_name">
          {{ object.name|title }}
        </div>
        <div class="category_actions">
          <button>
            <a href={% url 'adminapp:product_list' object.pk %}>
              товар категории
            </a>
          </button>
          <button>
            <a href={% url 'adminapp:category_edit' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'adminapp:category_delete' object.pk %}>
              удалить
            </a>
          </button>
        </div>
        <div class="category_desc">
          {{ object.description|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

my_shop/adminapp/templates/adminapp/category_create.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" class="btn btn-primary col-lg-12">
    </form>
    <button class="btn btn-warning col-lg-12" onclick="history.back()" >Назад</button>
{% endblock %}

my_shop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="">
    {% if object.is_active %}
        Уверены, что хотите удалить категорию? {{ object.title }}
    {% else %}
        Хотите восстановить категорию?
    {% endif %}
    </div>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Да">
    </form>
    <a href="{% url 'adminapp:category_list'%}" class="btn btn-success">НЕТ</a>
{% endblock %}

my_shop/adminapp/templates/adminapp/category_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" class="btn btn-primary col-lg-12">
    </form>
    <button class="btn btn-warning col-lg-12" onclick="history.back()">Назад</button>
{% endblock %}

my_shop/adminapp/templates/adminapp/product.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load tags %}
{% block content %}
  <div class="row">
    <button class="btn">
      <a href={% url 'adminapp:product_create' category.pk %}>
        новый продукт
      </a>
    </button>

    {% for object in object_list %}
      <div class="product_record {% if not object.is_active %}not_active{% endif %}">
        <img
          src="{{object.image|media_for_products}}"
          alt="{{ object.name }}">
        <div class="product_name">
          {{ object.name|title }}
        </div>
        <div class="product_actions">
          <button>
            <a href={% url 'adminapp:product_detail' object.pk %}>
              подробнее
            </a>
          </button>
          <button>
            <a href={% url 'adminapp:product_edit' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'adminapp:product_delete' object.pk %}>
              удалить
            </a>
          </button>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ object.price }} руб</p>
          <b>количество</b>
          <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ object.short_desc|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

my_shop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="">
    {% if object.is_active %}
        Уверены, что хотите удалить продукт? {{ object.get_full_name }}
    {% else %}
        Хотите восстановить продукт?
    {% endif %}
    </div>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Да">
    </form>
    <a href="{% url 'adminapp:product_list' object.category.pk %}" class="btn btn-success">НЕТ</a>
{% endblock %}

my_shop/adminapp/templates/adminapp/product_detail.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="product_read">
    <div class="product_name">
      Продукт<strong>{{ object.category.name|title }} /
                     {{ object.name|title }}</strong>
    </div>
    <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"
         alt="{{ object.name }}">
    <div class="summary">
      <b>цена</b>
      <p>{{ object.price }} руб</p>
      <b>количество</b>
      <p>{{ object.quantity }}</p>
      <b>в каталоге</b>
      <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
      <p>
        <button>
          <a href={% url 'adminapp:product_edit' object.pk %}>
            редактировать
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href={% url 'adminapp:product_delete' object.pk %}>
            удалить
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href={% url 'adminapp:product_list' object.category.pk %}>
            назад
          </a>
        </button>
      </p>
    </div>
    <div class="product_desc">
      <b>краткая информация</b>
      <p>{{ object.short_desc }}</p>
      <br><br>
      <b>подробная информация</b>
      <p>{{ object.description }}</p>
    </div>
  </div>
{% endblock %}

my_shop/adminapp/templates/adminapp/product_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" class="btn btn-primary col-lg-12">
    </form>
    <button class="btn btn-warning col-lg-12">Назад</button>
{% endblock %}

my_shop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="">
    {% if object.is_active %}
        Уверены, что хотите удалить пользователя? {{ object.get_full_name }}
    {% else %}
        Хотите восстановить пользователя?
    {% endif %}
    </div>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Да">
    </form>
    <a href="{% url 'adminapp:user_list' %}" class="btn btn-success">НЕТ</a>
{% endblock %}

my_shop/adminapp/templates/adminapp/user_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" class="btn btn-primary col-lg-12">
    </form>
    <button class="btn btn-warning col-lg-12">Назад</button>
{% endblock %}

my_shop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load tags %}
{% block content %}
    <div class="users_list">
        <button class="new_user">
            <a href={% url 'adminapp:user_create' %}>
                новый пользователь
            </a>
        </button>
        {% for object in object_list %}
            <div
                    class="user_record {% if not object.is_active %}not_active{% endif %}">
                <img
                        src="{{ object.avatar|media_for_users }}"
                        alt="{{ object.username }}">
                <div class="user_role">
                    {% if object.is_superuser %}
                        администратор
                    {% else %}
                        пользователь
                    {% endif %}
                    <button>
                        <a href={% url 'adminapp:user_edit' object.pk %}>
                            редактировать
                        </a>
                    </button>
                    <button>
                        <a href={% url 'adminapp:user_delete' object.pk %}>
                            {% if object.is_active %}
                                удалить
                            {% else %}
                                Восстановить
                            {% endif %}
                        </a>
                    </button>
                </div>
                <div class="user_name">
                    <p><strong>{{ object.username }}</strong></p>
                    <p>
                        {% if object.first_name %}
                            <b>{{ object.first_name|title }}</b>
                            {% if object.last_name %}
                                <p>{{ object.last_name|title }}</p>
                            {% endif %}
                        {% endif %}
                    </p>
                </div>
                <div class="user_age">
                    age:<br>
                    {{ object.age }} лет
                </div>
                <div class="user_email">
                    email:<br>
                    {{ object.email }}
                </div>
                <div class="user_lastlogin">
                    logged:<br>
                    {{ object.last_login }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}