my_shop/authapp/urls.py
from django.urls import path

from authapp.views import login, logout, register, edit, verify

app_name = 'authapp'
urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<email>/<key>/', verify, name='verify'),
]

my_shop/my_shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp

urlpatterns = [
    path('control/', admin.site.urls),

    path('', mainapp.index, name='index'),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('orderapp.urls', namespace='order'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

my_shop/authapp/models.py
from datetime import datetime, timedelta

import pytz
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True, verbose_name='Аватар')
    age = models.PositiveSmallIntegerField(verbose_name='Возраст')

    activate_key = models.CharField(max_length=128, verbose_name='Ключ активации', blank=True, null=True)
    activate_key_expired = models.DateTimeField(blank=True, null=True)

    def is_activate_key_expired(self):
        if datetime.now(pytz.timezone(settings.TIME_ZONE)) > self.activate_key_expired + timedelta(hours=48):
            return False
        return True

    def activate(self):
        self.is_active = True
        self.activate_key = None
        self.activate_key_expired = None
        self.save()


class ShopUserProfile(models.Model):
    MALE = 'm'
    WOMEN = 'w'
    OTHER = 'o'
    GENDER = (
        (MALE, 'М'),
        (WOMEN, 'Ж'),
        (OTHER, 'И'),
    )

    user = models.OneToOneField(ShopUser, null=False, unique=True, on_delete=models.CASCADE, db_index=True)
    tagline = models.CharField(max_length=128, verbose_name='Тэги', null=True, blank=True)
    about_name = models.TextField(verbose_name='Обо мне', blank=True, null=True)
    gender = models.CharField(choices=GENDER, default=MALE, max_length=1, verbose_name='Пол')

    @receiver(post_save, sender=ShopUser)
    def create_user_profile(sender, instance, created, *args, **kwargs):
        if created:
            ShopUserProfile.objects.create(user=instance)

    @receiver(post_save, sender=ShopUser)
    def update_user_profile(sender, instance, **kwargs):
        instance.shopuserprofile.save()

my_shop/authapp/forms.py
import hashlib

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.conf import settings
from django.forms import HiddenInput, forms
from authapp.models import ShopUser, ShopUserProfile
from django import forms
from datetime import datetime

import pytz


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Слишком мелкий')
        return data


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'avatar', 'email', 'age', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def save(self, *args, **kwargs):
        user = super().save(*args, **kwargs)
        user.is_active = False
        user.activate_key = hashlib.sha1(user.email.encode('utf-8')).hexdigest()[:6]
        user.activate_key_expired = datetime.now(pytz.timezone(settings.TIME_ZONE))
        user.save()
        return user


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'avatar', 'email', 'age', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.widgets.CheckboxInput):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'

            if field_name == 'password':
                field.widget = HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Слишком мелкий')
        return data


class ShopUserProfileEditForm(forms.ModelForm):
    class Meta:
        model = ShopUserProfile
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

my_shop/authapp/views.py
import pytz
from django.shortcuts import render
from django.contrib import auth
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.urls import reverse

from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm, ShopUserProfileEditForm
from authapp.models import ShopUser
from authapp.services import send_verify_email


def login(request):
    login_form = ShopUserLoginForm(data=request.POST)
    next_param = request.GET.get('next', '')
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            return HttpResponseRedirect(reverse('index'))
    context = {
        'login_form': login_form,
        'next_param': next_param
    }

    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            new_user = register_form.save()
            send_verify_email(new_user)
            return HttpResponseRedirect(reverse('index'))
    else:
        register_form = ShopUserRegisterForm()
    context = {
        'register_form': register_form
    }
    return render(request, 'authapp/register.html', context)


def edit(request):
    if request.method == 'POST':
        user_edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        user_profile_form = ShopUserProfileEditForm(request.POST, instance=request.user.shopuserprofile)
        if user_edit_form.is_valid() and user_profile_form.is_valid():
            user_edit_form.save()
            return HttpResponseRedirect(reverse('index'))
    else:
        user_edit_form = ShopUserEditForm(instance=request.user)
        user_profile_form = ShopUserProfileEditForm(instance=request.user.shopuserprofile)

    context = {
        'user_edit_form': user_edit_form,
        'user_profile_form': user_profile_form,
    }
    return render(request, 'authapp/edit.html', context)


def verify(request, email, key):
    user = ShopUser.objects.filter(email=email).first()
    if user:
        if user.activate_key == key and user.is_activate_key_expired():
            user.activate()
            auth.login(request, user)
    return render(request, 'authapp/register_result.html')

my_shop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.rtl.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static '/js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static '/js/basket.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="login">
        <div class="h2 text-center head">
            Вход в систему
        </div>

        {% block content %}

        {% endblock %}
    </div>
</div>
</body>
</html>

my_shop/authapp/templates/authapp/edit.html
{%extends 'authapp/base.html'%}
{%load static%}

{%block content%}
    {% if user.avatar %}
        <img src="/media/{{user.avatar}}">
    {% else %}
        <img src="{{ user.avatar_urls }}">
    {% endif %}
<form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{user_edit_form.as_p}}
    {{user_profile_form.as_p}}
    <input type="submit" class="btn btn-primary" value="Сохранить">
</form>
{% endblock %}

my_shop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        {% if next_param %}
            <input type="hidden" name="next" value={{ next_param }}>
        {% endif %}
        <input type="submit" class="btn btn-primary" value="Войти">
    </form>
    <hr>
    <a href="{% url 'auth:register' %}" class="btn btn-link">Регистрация</a><br>
    <a  class="btn btn-link" href="{% url 'social:begin' 'vk-oauth2'%}?next=/">Вход через VK</a><br>

{% endblock %}

my_shop/authapp/templates/authapp/register.html
{%extends 'authapp/base.html'%}
{%load static%}

{%block content%}
<form class="form-horizontal" action="{% url 'auth:register' %}" method ="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{register_form.as_p}}
    <input type="submit" class="btn btn-primary" value="Зарегистрироваться">
    <hr>
    <a href="{% url 'auth:login' %}">Войти</a>
</form>
{% endblock %}

my_shop/authapp/templates/authapp/register_result.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
    {% if user.is_authenticated %}
        <h1>Поздравляем, вы успешно зарегистрировались!</h1>
    {% else %}
        <h1>Что-то пошло не так!</h1>
    {% endif %}
    <a href="{% url 'index' %}">На главную</a>
{% endblock %}